[package]
name = "honkoku-ocr"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["process", "io-util", "fs"] }
sha2 = "0.10"
honkoku-core.workspace = true
honkoku-storage.workspace = true
honkoku-iiif.workspace = true
time.workspace = true
tempfile = "3"

