import { presets } from "./presets";
export const palette = [
  {
    label: "踊り字",
    characters: [
      "々",
      "ゝ",
      "ゞ",
      "ヽ",
      "ヾ",
      "〻",
      "〱",
      "〲",
      "〳",
      "〴",
      "〵",
    ],
  },
  { label: "合字", characters: ["ゟ", "ヿ", "〆"] },
  { label: "変体仮名", characters: ["𛀀", "𛀁", "𛀂", "𛀆", "𛀙", "𛁛", "𬼂"] },
  { label: "欠字", characters: ["■", "□", "〓"] },
  {
    label: "返り点",
    characters: [
      "＿レ",
      "＿一",
      "＿二",
      "＿三",
      "＿上",
      "＿中",
      "＿下",
      "＿甲",
      "＿乙",
      "＿丙",
      "＿天",
      "＿地",
      "＿人",
    ],
  },
  { label: "送り仮名", characters: presets.送り仮名.map((p) => p.text) },
  { label: "常用字", characters: presets.常用字.map((p) => p.text) },
  { label: "常用句", characters: presets.常用句.map((p) => p.text) },
  {
    label: "記号",
    characters: ["・", "○", "●", "△", "※", "／", "「", "」", "〔", "〕"],
  },
] as const;
